### ISSUE TITLE
Uncaught TypeError: Illegal offset type in isset or empty

### ISSUE THREAD

**Issue by coudenysj** [CMS-Garden/cmsscanner#81]
Hi,

First of all, thank you for this great scanner :).

I'm seeing this error from time to time:
```
Fatal error: Uncaught TypeError: Illegal offset type in isset or empty in phar:///usr/src/scanner/cmsscanner.phar/src/Command/DetectCommand.php:228
Stack trace:
#0 phar:///usr/src/scanner/cmsscanner.phar/src/Command/DetectCommand.php(142): Cmsgarden\Cmsscanner\Command\DetectCommand->generateStats(Array, true, true)
#1 phar:///usr/src/scanner/cmsscanner.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Cmsgarden\Cmsscanner\Command\DetectCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///usr/src/scanner/cmsscanner.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(889): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///usr/src/scanner/cmsscanner.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(Cmsgarden\Cmsscanner\Command\DetectCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

///usr/src/scanner/cmsscanner.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///usr/src/scanner/cmsscanner.phar/bin/cmsscanner(18): Symfony\Component\Console\Application->run()
#6 /usr/src/scanner/cmsscanner.phar(10): require('phar:///usr/src...')

}
  thrown in phar:///usr/src/scanner/cmsscanner.phar/src/Command/DetectCommand.php on line 228
```

Should the value be tested before using it? 
https://github.com/CMS-Garden/cmsscanner/blob/cbedf20bf196cf3cd9e8854a4658d860f1d1a1a4/src/Command/DetectCommand.php#L228

**Comment by SniperSister** [comment]
@coudenysj do you have some context when that issue occurs? At the first glance it looks like either $systemName or $item->name is not a string, however I'm wondering how this could happen...

**Comment by coudenysj** [comment]
Looks like $item->name is an array sometimes:

```
string(17) "Akismet Anti-Spam"
string(11) "Hello Dolly"
string(14) "LayerSlider WP"
array(2) {
  [0]=>
  string(44) "
"lugin Name: Allow PHP in Posts and Pages
  [1]=>
" string(29) "Allow PHP in Posts and Pages
}
PHP Warning:  Illegal offset type in isset or empty in /cmsscanner/cmsscanner/src/Command/DetectCommand.php on line 228
PHP Warning:  Illegal offset type in /cmsscanner/cmsscanner/src/Command/DetectCommand.php on line 229
PHP Warning:  Illegal offset type in /cmsscanner/cmsscanner/src/Command/DetectCommand.php on line 232
string(7) "bbPress"
```

**Comment by SniperSister** [comment]
@coudenysj that looks like a specific WP plugin is causing the issue, however I can't see how as the name is returned from a regex that supposed to return just one value, not an array of values:

https://github.com/CMS-Garden/cmsscanner/blob/develop/src/Detector/Adapter/WordpressAdapter.php#L114

Any idea?
